import { Inter } from "next/font/google";
import GlobalStyle from "./components/atoms/GlobalStyles";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NASA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStyle />
        {children}
      </body>
    </html>
  );
}
