import GlobalStyle from "../../components/atoms/GlobalStyles";

export const metadata = {
  title: "NASA",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale}>
      <body>
        <GlobalStyle />
        {children}
      </body>
    </html>
  );
}
